#!/bin/bash

set -e

if [ "$#" -ne 3 ]; then
    echo "$0 <local_file> <bucket_name> <expiration_seconds>"
    exit 1
fi

LOCAL_FILE=$1
BUCKET_NAME=$2
EXPIRATION=$3

aws s3 cp "$LOCAL_FILE" "s3://$BUCKET_NAME/"

PRESIGNED_URL=$(aws s3 presign --expires-in "$EXPIRATION" "s3://$BUCKET_NAME/$(basename "$LOCAL_FILE")")

echo "$PRESIGNED_URL"
